# This workflow should build the website with Hugo and deploy it on
# GitHub pages. Edit this file as you wish, otherwise just make sure
# that this folder contains a workflow exists that it is executed
# upon pushing the source to the default branch.

name: Build and deploy GitHub pages with Hugo

# The rest of the workflow is only provided as a minimal example that
# does not produce any errors on GitHub. It should be modified to
# fulfil the project requirements.

# A workflow that only runs during leap years

on:
  push:
    branches:
      - master
  pull_request:

# Sample job that does nothing

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          # extended: true

      - name: Build
        run: cd website && hugo --minify

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: website/public # The folder the action should deploy.
